VetCompass/authentication/urls.py
from django.urls import path

from . import views

app_name = 'authentication'


urlpatterns = [

    path('', views.index, name='index'),
]

VetCompass/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('login/', include('authentication.urls')),
    path('research/', include('research.urls')),
    path('admin/', admin.site.urls),

    path("", include('public.urls'))
]

VetCompass/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.index, name='index'),
    # ex: /polls/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

VetCompass/research/urls.py
from django.urls import path

from . import views

app_name = 'authentication'

urlpatterns = [
    path('', views.index, name='index'),
]

VetCompass/authentication/models.py
from django.db import models

# Create your models here.

VetCompass/polls/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)



class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

VetCompass/research/models.py
from django.db import models

# Create your models here.

VetCompass/authentication/views.py
from django.shortcuts import render

from django.http import HttpResponse
from django.template import loader
from django.contrib.auth import authenticate


def index(request):

    # check request method for page redirect
    if request.method == "GET":
        template = loader.get_template('authentication/index.html')
        context = {}
        return HttpResponse(template.render(context, request))
    else:
        return verify(request)


# verify user account and password
def verify(request):

    username = request.POST.get('username','')
    password = request.POST.get('password','')

    # check username and password match in database
    user = authenticate(username=username, password=password)

    if user is not None:
        return HttpResponse("correct username or password")
    else:
        return HttpResponse("wrong username and password",status=401)

VetCompass/polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.template import loader
from .models import Question
from django.http import Http404




def index(request):
    # request
    # user = User.objects.create_user('john', 'lennon@thebeatles.com', 'johnpassword')
    # user.last_name = 'Lennon'
    # user.save()
    # print(type(request))
    # return HttpResponse("Hello, world. You're at the polls indexkds.", request.body)

    # if request.method == 'GET':
    #     return HttpResponse("Hello, world. You're at the polls indexkds. GET")
    # else:
    #     return HttpResponse("Hello, world. You're at the polls indexkds.", "POST")

    latest_question_list = Question.objects.order_by('-pub_date')[:5]

    # output = ', '.join([q.question_text for q in latest_question_list])

    # template = loader.get_template('polls/index.html')
    #
    # context = {
    #     'latest_question_list': latest_question_list,
    # }

    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

    # return HttpResponse(template.render(context, request))



def detail(request, question_id):
    # try:
    #     question = Question.objects.get(pk=question_id)
    # except Question.DoesNotExist:
    #     raise Http404("Question does not exist")
    # return render(request, 'polls/detail.html', {'question': question})

    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})


def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)


def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

VetCompass/research/views.py
from django.shortcuts import render

from django.http import HttpResponse


def index(request):
    return HttpResponse("Hello, This is a research site, index")

VetCompass/authentication/templates/authentication/index.html
<form action="{% url 'authentication:index' %}" method="post">
{% csrf_token %}

  Username:<br>
  <input type="text" name="username" >
  <br>
  Password:<br>
  <input type="text" name="password" >
  <br><br>
  <input type="submit" value="Submit">

</form>

VetCompass/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>

<br>

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

VetCompass/polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}